Controllers/ApplicantsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InternshipDotCom.Models;
using InternshipDotCom.Servieces;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;

namespace InternshipDotCom.Controllers
{
    [Authorize (Roles = "applicant")]
    public class ApplicantsController : Controller
    {
        private readonly ApplicationDbContext _context;


        private readonly IWebHostEnvironment _webHostEnvironment;
        public ApplicantsController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;

            _webHostEnvironment = webHostEnvironment;

        
        }



        public async Task<IActionResult> PostedInternship()
        {

            var allOrganizations = await _context.Organization.ToListAsync();


            ViewBag.Organizations = allOrganizations;


            var allInternships = await _context.Internship
                .Include(i => i.Organization)
                .ToListAsync();
            

            ViewBag.AllInternships = allInternships;
            if (allInternships.Count == 0)
            {
                return View("SaveOrApplyInternships");
            }

            return View(allInternships);

        }


        public async Task<IActionResult> AppliedInternships()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
           
            var appliedOrganizations = await _context.ApplicantInternship
                .Where(ai => ai.ApplicationUserId == userId && ai.IsApplied)
                .Select(ai => ai.Internship.Organization)
                .Distinct()
                .ToListAsync();

            ViewBag.Organizations = appliedOrganizations;

            var appliedInternships = await _context.ApplicantInternship
                .Include(ai => ai.Internship)
                    .ThenInclude(i => i.Organization)
                .Where(ai => ai.ApplicationUserId == userId && ai.IsApplied)
                .Select(ai => ai.Internship)
                .ToListAsync();

            if (appliedInternships.Count == 0)
            {
                return View("SaveOrApplyInternships");
            }
            ViewBag.AllInternships = appliedInternships;
            return View(appliedInternships);
        }

        public async Task<IActionResult> SavedInternships()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
          
            var savedOrganizations = await _context.ApplicantInternship
                .Where(ai => ai.ApplicationUserId == userId && ai.IsSaved)
                .Select(ai => ai.Internship.Organization)
                .Distinct()
                .ToListAsync();

            ViewBag.Organizations = savedOrganizations;

            var savedInternships = await _context.ApplicantInternship
                .Include(ai => ai.Internship)
                .ThenInclude(i => i.Organization)
                .Where(ai => ai.ApplicationUserId == userId && ai.IsSaved)
                .Select(ai => ai.Internship)
                .ToListAsync();
            if (savedInternships.Count == 0)
            {
                return View("SaveOrApplyInternships");
            }
            ViewBag.AllInternships = savedInternships;
            return View(savedInternships);
        }


        public async Task<IActionResult> Filter(int? organizationId)
        {

            var allOrganizations = await _context.Organization.ToListAsync();


            ViewBag.Organizations = allOrganizations;


            var internshipsQuery = _context.Internship
                .Include(i => i.Organization)
                .AsQueryable();


            if (organizationId.HasValue)
            {
                internshipsQuery = internshipsQuery.Where(i => i.OrganizationId == organizationId);
            }


            var filteredInternships = await internshipsQuery.ToListAsync();


            return PartialView("_InternshipTable", filteredInternships);

        }


        public async Task<IActionResult> FilterApplied(int? organizationId)
        {
            var allOrganizations = await _context.Organization.ToListAsync();
            ViewBag.Organizations = allOrganizations;

            var applicationUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var appliedInternshipsQuery = _context.ApplicantInternship
                .Where(ai => ai.ApplicationUserId == applicationUserId && ai.IsApplied)
                .Select(ai => ai.InternshipId);
 
            var internshipsQuery = _context.Internship
                .Where(i => appliedInternshipsQuery.Contains(i.Id))
                .Include(i => i.Organization)
                .AsQueryable();

            if (organizationId.HasValue)
            {
                internshipsQuery = internshipsQuery.Where(i => i.OrganizationId == organizationId);
            }

            var filteredInternships = await internshipsQuery.ToListAsync();

            return PartialView("_AppliedInternshipTable", filteredInternships);
        }

        public async Task<IActionResult> FilterSaved(int? organizationId)
        {
            var allOrganizations = await _context.Organization.ToListAsync();
            ViewBag.Organizations = allOrganizations;

            var applicationUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            // Get saved internships for the current user
            var savedInternshipsQuery = _context.ApplicantInternship
                .Where(ai => ai.ApplicationUserId == applicationUserId && ai.IsSaved)
                .Select(ai => ai.InternshipId);

            // Query internships based on the saved internships for the current user
            var internshipsQuery = _context.Internship
                .Where(i => savedInternshipsQuery.Contains(i.Id))
                .Include(i => i.Organization)
                .AsQueryable();

            // Apply organization filter if provided
            if (organizationId.HasValue)
            {
                internshipsQuery = internshipsQuery.Where(i => i.OrganizationId == organizationId);
            }

            // Get the filtered internships
            var filteredInternships = await internshipsQuery.ToListAsync();

            // Return the filtered internships as a partial view
            return PartialView("_SavedInternshipTable", filteredInternships);
        }



        public async Task<IActionResult> Apply(int id)
        {
            var internship = _context.Internship.FirstOrDefault(i => i.Id == id);
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            bool isApplied = await _context.ApplicantInternship.AnyAsync(ai => ai.ApplicationUserId == userId && ai.InternshipId == id && ai.IsApplied);

            
         

            if (internship == null)
            {
                return NotFound();
            }

            if (isApplied)
            {
                TempData["successMessage"] = "You have already applied for this internship.";
                return RedirectToAction("AppliedInternships");
            }

            var currentUser = _context.Users.FirstOrDefault(u => u.Id == userId);

            ViewBag.FirstName = currentUser.FristName;
            ViewBag.LastName = currentUser.LastName;
            ViewBag.ApplicationUserId = userId;
            ViewBag.InternshipId = id;

            var universities = _context.University
                .Where(u => u.id != 1)
                .ToList();
            var universityListItems = universities.Select(u => new SelectListItem
            {
                Value = u.id.ToString(), 
                Text = u.name 
            }).ToList();     
            ViewBag.UniversityId = universityListItems;


            var departments = _context.Department
               .Where(d => d.Id != 1)
               .ToList();

            var departmentsListItems = departments.Select(u => new SelectListItem
            {
                Value = u.Id.ToString(),
                Text = u.Name
            }).ToList();

            ViewBag.DepartmentId = departmentsListItems;


            var yearOfstudy = _context.YearOfStudy.ToList();
            var yearOfstudyListItems = yearOfstudy.Select(u => new SelectListItem
            {
                Value = u.Id.ToString(),
                Text = u.Year
            }).ToList();
            ViewBag.YearOfStudyId = yearOfstudyListItems;

            var applicantInternship = new ApplicantInternship();

            return View(applicantInternship);
        }





        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ApplyForInternship(ApplicantInternship applicantInternship)
        {

            bool internshipExist = await _context.ApplicantInternship.AnyAsync(ai => ai.ApplicationUserId == applicantInternship.ApplicationUserId && ai.InternshipId == applicantInternship.InternshipId);

            if (internshipExist)
            {
                var existingApplication = await _context.ApplicantInternship.FirstOrDefaultAsync(ai => ai.ApplicationUserId == applicantInternship.ApplicationUserId && ai.InternshipId == applicantInternship.InternshipId);

                existingApplication.FirstName = applicantInternship.FirstName;
                existingApplication.LastName = applicantInternship.LastName;
                existingApplication.DepartmentId = applicantInternship.DepartmentId;
                existingApplication.UniversityId = applicantInternship.UniversityId;
                existingApplication.YearOfStudyId = applicantInternship.YearOfStudyId;
                existingApplication.CoverLetter = applicantInternship.CoverLetter;
                existingApplication.IsApplied = true;

Controllers/DepartmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InternshipDotCom.Models;
using InternshipDotCom.Servieces;
using Microsoft.AspNetCore.Authorization;

namespace InternshipDotCom.Controllers
{
    [Authorize(Roles = "admin")]
    public class DepartmentsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DepartmentsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Departments
        public async Task<IActionResult> Index()
        {
            return View(await _context.Department.ToListAsync());
        }

        // GET: Departments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var department = await _context.Department
                .FirstOrDefaultAsync(m => m.Id == id);
            if (department == null)
            {
                return NotFound();
            }

            return View(department);
        }

        // GET: Departments/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Departments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Department department)
        {
            if (ModelState.IsValid)
            {
                _context.Add(department);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(department);
        }

        // GET: Departments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var department = await _context.Department.FindAsync(id);
            if (department == null)
            {
                return NotFound();
            }
            return View(department);
        }

        // POST: Departments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Department department)
        {
            if (id != department.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(department);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DepartmentExists(department.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(department);
        }

        // GET: Departments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var department = await _context.Department
                .FirstOrDefaultAsync(m => m.Id == id);
            if (department == null)
            {
                return NotFound();
            }

            return View(department);
        }

        // POST: Departments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var department = await _context.Department.FindAsync(id);
            if (department != null)
            {
                _context.Department.Remove(department);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DepartmentExists(int id)
        {
            return _context.Department.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InternshipDotCom</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InternshipDotCom.styles.css" asp-append-version="true" />
</head>
<body>
    <header >
        <div class="row  bg-white border-bottom box-shadow mb-3">
            <nav class="col-sm-11 navbar navbar-expand-sm navbar-toggleable-sm navbar-light" style="background-color:#D3E3FD">
                <div class="container-fluid ">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">InternshipDotCom</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between" >
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                
                            </li>
                            @if (User.IsInRole("admin"))
                            {

                                <li class="nav-item dropdown ">
                                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        University
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a class="dropdown-item" asp-controller="Universities" asp-action="Index">View</a></li>
                                        <li><a class="dropdown-item" asp-controller="Universities" asp-action="Create">Add New</a></li>
                                    </ul>
                                </li>

                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Department
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a class="dropdown-item" asp-controller="Departments" asp-action="Index">View</a></li>
                                        <li><a class="dropdown-item" asp-controller="Departments" asp-action="Create">Add New</a></li>
                                    </ul>
                                </li>

                                <li class="nav-item dropdown ">
                                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Dep't Coordinator
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a class="dropdown-item" asp-controller="AssignedCoordinators" asp-action="Index">View</a></li>
                                        <li><a class="dropdown-item" asp-controller="AssignedCoordinators" asp-action="Create">Assign</a></li>
                                    </ul>
                                </li>
                            }
                            @if (User.IsInRole("organization"))
                            {

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Internships" asp-action="Index">Internship</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Organizations" asp-action="Index">Company</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Organizations" asp-action="ViewRegisteredStudents">Applicants</a>
                                </li>
                            }
                            @if (User.IsInRole("applicant"))
                            {

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Applicants" asp-action="PostedInternship">Internships</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Applicants" asp-action="AppliedInternships">Registerd</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Applicants" asp-action="SavedInternships">Saved</a>
                                </li>
                            }

                            @if (User.IsInRole("InternshipCordinator"))
                            {

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="ApplicantStatus" asp-action="Index">Applicants</a>
                                </li>
                            }
                        </ul>
                     <partial name="_LoginPartial" />
                </div> 
            </div>
          </nav>
            <div class="col-sm-1" style="background-color: #D3E3FD"></div>
        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
             @{
                var errorMessage = TempData["errorMassage"]?.ToString();
                var successMessage = TempData["successMessage"]?.ToString();
            }
            @if (!string.IsNullOrWhiteSpace(@successMessage))
            {
                <div class="alert alert-success">
                    <b>Success : </b>@successMessage
                    <button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="Close"></button>

                </div>
            }
            else if (!string.IsNullOrWhiteSpace(@errorMessage))
            {
                <div class="alert alert-danger">
                    <b>Error : </b>@errorMessage
                    <button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            }

            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - InternshipDotCom - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/js/closealertauthomatically.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>