Controllers/ApplicantStatusController.cs
using System.Linq;
using InternshipDotCom.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using InternshipDotCom.Servieces;

namespace InternshipDotCom.Controllers
{
    [Authorize(Roles = "InternshipCordinator")]
    public class ApplicantStatusController : Controller
    {
        private readonly ApplicationDbContext _context;
        

        public ApplicantStatusController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            
        }

        public IActionResult Index()
        {

            var AllYear = _context.YearOfStudy.ToList();
            ViewBag.Year = AllYear;
            // Get the current user's ID
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            // Find the coordinator's department and university
            var coordinator = _context.AssignedCoordinator
                .Include(ac => ac.ApplicationUser)
                .Include(ac => ac.university)
                .Include(ac => ac.department)
                .FirstOrDefault(ac => ac.ApplicationUserId == userId);

            if (coordinator == null)
            {
                return View("NotAssigned");
            }

            // Get the coordinator's department and university IDs
            var coordinatorDepartmentId = coordinator.DepartmentId;
            var coordinatorUniversityId = coordinator.UniversityId;

            

            // Query applicants whose department and university match those of the coordinator
            var matchingApplicants = _context.ApplicantInternship
                .Include(ai => ai.ApplicationUser)
                .Include(ai => ai.university)
                .Include(ai => ai.department)
                .Where(ai => ai.DepartmentId == coordinatorDepartmentId && ai.UniversityId == coordinatorUniversityId && ai.IsApplied)
                .ToList();

            return View(matchingApplicants);
        }

        public async Task<IActionResult> GetApplicantDetails(int applicantId)
        {
            var applicant = await _context.ApplicantInternship
                .Include(ai => ai.ApplicationUser)
                .Include(ai => ai.university)
                .Include(ai => ai.department)
                .Include(ai => ai.YearOfStudy)
                .FirstOrDefaultAsync(ai => ai.Id == applicantId);

            if (applicant == null)
            {
                return NotFound();
            }

            return PartialView("_ApplicantDetails", applicant);
        }

        public async Task<IActionResult> Filter(int? YearId)
        {


            var AllYear = _context.YearOfStudy.ToList();
            ViewBag.Year = AllYear;

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            // Find the coordinator's department and university
            var coordinator = _context.AssignedCoordinator
                .Include(ac => ac.ApplicationUser)
                .Include(ac => ac.university)
                .Include(ac => ac.department)
                .FirstOrDefault(ac => ac.ApplicationUserId == userId);

            if (coordinator == null)
            {
                return View("NotAssigned");
            }

            // Get the coordinator's department and university IDs
            var coordinatorDepartmentId = coordinator.DepartmentId;
            var coordinatorUniversityId = coordinator.UniversityId;



            // Query applicants whose department and university match those of the coordinator
          
            var ApplicantQuery = _context.ApplicantInternship
                .Include(i => i.YearOfStudy)
                .Include(i => i.ApplicationUser)
                .AsQueryable();


            if (YearId.HasValue)
            {
                ApplicantQuery = ApplicantQuery.Where(i => i.YearOfStudyId == YearId && i.DepartmentId == coordinatorDepartmentId && i.UniversityId == coordinatorUniversityId && i.IsApplied);
            }


            var filteredApplicant = await ApplicantQuery.ToListAsync();


            return PartialView("_ApplicantTable", filteredApplicant);

        }

        public IActionResult Search(string SearchedUsername)
        {
            var AllYear = _context.YearOfStudy.ToList();
            ViewBag.Year = AllYear;
            // Get the current user's ID
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            // Find the coordinator's department and university
            var coordinator = _context.AssignedCoordinator
                .Include(ac => ac.ApplicationUser)
                .Include(ac => ac.university)
                .Include(ac => ac.department)
                .FirstOrDefault(ac => ac.ApplicationUserId == userId);

            if (coordinator == null)
            {
                return View("NotAssigned");
            }

            // Get the coordinator's department and university IDs
            var coordinatorDepartmentId = coordinator.DepartmentId;
            var coordinatorUniversityId = coordinator.UniversityId;



            // Query applicants whose department and university match those of the coordinator
            var matchingApplicants = _context.ApplicantInternship
                .Include(ai => ai.ApplicationUser)
                .Include(ai => ai.university)
                .Include(ai => ai.department)
                .Where(ai => ai.DepartmentId == coordinatorDepartmentId && ai.UniversityId == coordinatorUniversityId && ai.ApplicationUser.UserName == SearchedUsername && ai.IsApplied)
                .ToList();

            return PartialView("_ApplicantTable", matchingApplicants);


        }

        }
}

Controllers/ApplicantsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InternshipDotCom.Models;
using InternshipDotCom.Servieces;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;

namespace InternshipDotCom.Controllers
{
    [Authorize (Roles = "applicant")]
    public class ApplicantsController : Controller
    {
        private readonly ApplicationDbContext _context;


        private readonly IWebHostEnvironment _webHostEnvironment;
        public ApplicantsController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;

            _webHostEnvironment = webHostEnvironment;

        
        }



        public async Task<IActionResult> PostedInternship()
        {

            var allOrganizations = await _context.Organization.ToListAsync();


            ViewBag.Organizations = allOrganizations;


            var allInternships = await _context.Internship
                .Include(i => i.Organization)
                .ToListAsync();
            

            ViewBag.AllInternships = allInternships;
            if (allInternships.Count == 0)
            {
                return View("SaveOrApplyInternships");
            }

            return View(allInternships);

        }


        public async Task<IActionResult> AppliedInternships()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
           
            var appliedOrganizations = await _context.ApplicantInternship
                .Where(ai => ai.ApplicationUserId == userId && ai.IsApplied)
                .Select(ai => ai.Internship.Organization)
                .Distinct()
                .ToListAsync();

            ViewBag.Organizations = appliedOrganizations;

            var appliedInternships = await _context.ApplicantInternship
                .Include(ai => ai.Internship)
                    .ThenInclude(i => i.Organization)
                .Where(ai => ai.ApplicationUserId == userId && ai.IsApplied)
                .Select(ai => ai.Internship)
                .ToListAsync();

            if (appliedInternships.Count == 0)
            {
                return View("SaveOrApplyInternships");
            }
            ViewBag.AllInternships = appliedInternships;
            return View(appliedInternships);
        }

        public async Task<IActionResult> SavedInternships()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
          
            var savedOrganizations = await _context.ApplicantInternship
                .Where(ai => ai.ApplicationUserId == userId && ai.IsSaved)
                .Select(ai => ai.Internship.Organization)
                .Distinct()
                .ToListAsync();

            ViewBag.Organizations = savedOrganizations;

            var savedInternships = await _context.ApplicantInternship
                .Include(ai => ai.Internship)
                .ThenInclude(i => i.Organization)
                .Where(ai => ai.ApplicationUserId == userId && ai.IsSaved)
                .Select(ai => ai.Internship)
                .ToListAsync();
            if (savedInternships.Count == 0)
            {
                return View("SaveOrApplyInternships");
            }
            ViewBag.AllInternships = savedInternships;
            return View(savedInternships);
        }


        public async Task<IActionResult> Filter(int? organizationId)
        {

            var allOrganizations = await _context.Organization.ToListAsync();


            ViewBag.Organizations = allOrganizations;


            var internshipsQuery = _context.Internship
                .Include(i => i.Organization)
                .AsQueryable();


            if (organizationId.HasValue)
            {
                internshipsQuery = internshipsQuery.Where(i => i.OrganizationId == organizationId);
            }


            var filteredInternships = await internshipsQuery.ToListAsync();


            return PartialView("_InternshipTable", filteredInternships);

        }


        public async Task<IActionResult> FilterApplied(int? organizationId)
        {
            var allOrganizations = await _context.Organization.ToListAsync();
            ViewBag.Organizations = allOrganizations;

            var applicationUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var appliedInternshipsQuery = _context.ApplicantInternship
                .Where(ai => ai.ApplicationUserId == applicationUserId && ai.IsApplied)
                .Select(ai => ai.InternshipId);
 
            var internshipsQuery = _context.Internship
                .Where(i => appliedInternshipsQuery.Contains(i.Id))
                .Include(i => i.Organization)
                .AsQueryable();

            if (organizationId.HasValue)
            {
                internshipsQuery = internshipsQuery.Where(i => i.OrganizationId == organizationId);
            }

            var filteredInternships = await internshipsQuery.ToListAsync();

            return PartialView("_AppliedInternshipTable", filteredInternships);
        }

        public async Task<IActionResult> FilterSaved(int? organizationId)
        {
            var allOrganizations = await _context.Organization.ToListAsync();
            ViewBag.Organizations = allOrganizations;

            var applicationUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            // Get saved internships for the current user
            var savedInternshipsQuery = _context.ApplicantInternship
                .Where(ai => ai.ApplicationUserId == applicationUserId && ai.IsSaved)
                .Select(ai => ai.InternshipId);

            // Query internships based on the saved internships for the current user
            var internshipsQuery = _context.Internship
                .Where(i => savedInternshipsQuery.Contains(i.Id))
                .Include(i => i.Organization)
                .AsQueryable();

            // Apply organization filter if provided
            if (organizationId.HasValue)
            {
                internshipsQuery = internshipsQuery.Where(i => i.OrganizationId == organizationId);
            }

            // Get the filtered internships
            var filteredInternships = await internshipsQuery.ToListAsync();

            // Return the filtered internships as a partial view
            return PartialView("_SavedInternshipTable", filteredInternships);
        }



        public async Task<IActionResult> Apply(int id)
        {
            var internship = _context.Internship.FirstOrDefault(i => i.Id == id);
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            bool isApplied = await _context.ApplicantInternship.AnyAsync(ai => ai.ApplicationUserId == userId && ai.InternshipId == id && ai.IsApplied);

            
         

            if (internship == null)
            {
                return NotFound();
            }

            if (isApplied)
            {
                TempData["successMessage"] = "You have already applied for this internship.";
                return RedirectToAction("AppliedInternships");
            }

            var currentUser = _context.Users.FirstOrDefault(u => u.Id == userId);

            ViewBag.FirstName = currentUser.FristName;
            ViewBag.LastName = currentUser.LastName;
            ViewBag.ApplicationUserId = userId;
            ViewBag.InternshipId = id;

            var universities = _context.University
                .Where(u => u.id != 1)
                .ToList();
            var universityListItems = universities.Select(u => new SelectListItem
            {
                Value = u.id.ToString(), 
                Text = u.name 
            }).ToList();     
            ViewBag.UniversityId = universityListItems;


            var departments = _context.Department
               .Where(d => d.Id != 1)
               .ToList();

            var departmentsListItems = departments.Select(u => new SelectListItem
            {
                Value = u.Id.ToString(),
                Text = u.Name
            }).ToList();

            ViewBag.DepartmentId = departmentsListItems;


            var yearOfstudy = _context.YearOfStudy.ToList();
            var yearOfstudyListItems = yearOfstudy.Select(u => new SelectListItem
            {
                Value = u.Id.ToString(),
                Text = u.Year
            }).ToList();
            ViewBag.YearOfStudyId = yearOfstudyListItems;

            var applicantInternship = new ApplicantInternship();

            return View(applicantInternship);
        }





        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ApplyForInternship(ApplicantInternship applicantInternship)
        {

            bool internshipExist = await _context.ApplicantInternship.AnyAsync(ai => ai.ApplicationUserId == applicantInternship.ApplicationUserId && ai.InternshipId == applicantInternship.InternshipId);

            if (internshipExist)
            {
                var existingApplication = await _context.ApplicantInternship.FirstOrDefaultAsync(ai => ai.ApplicationUserId == applicantInternship.ApplicationUserId && ai.InternshipId == applicantInternship.InternshipId);

                existingApplication.FirstName = applicantInternship.FirstName;
                existingApplication.LastName = applicantInternship.LastName;
                existingApplication.DepartmentId = applicantInternship.DepartmentId;
                existingApplication.UniversityId = applicantInternship.UniversityId;
                existingApplication.YearOfStudyId = applicantInternship.YearOfStudyId;
                existingApplication.CoverLetter = applicantInternship.CoverLetter;
                existingApplication.IsApplied = true;

Views/ApplicantStatus/Index.cshtml
@model List<InternshipDotCom.Models.ApplicantInternship>

@{
    ViewData["Title"] = "Matching Applicants";
}

<style>
    .view-details-link {
        color: #007bff;
        text-decoration: none;
        border: 1px solid #007bff;
        padding: 5px 10px;
        border-radius: 5px;
        transition: background-color 0.3s ease;
        background-color: rgba(0, 123, 255, 0.1);
    }

        .view-details-link:hover {
            background-color: rgba(0, 123, 255, 0.2);
            color: #007bff;
        }

    .search-icon {
        background-color: #007bff;
        color: #fff;
        padding: 10px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        transition: background-color 0.3s ease;
    }

        .search-icon:hover {
            background-color: #0056b3;
        }
</style>

<div class="row">

    <div class="col-sm-9">
    <div class="row align-items-left">
        <div class="col-md-2">
            <label for="ApplicantFilter" class="form-label">By Year:</label>
        </div>
        <div class="col-md-4" style="margin-left:-83px;">
            <select id="ApplicantFilter" class="form-select">
                <option value="">All</option>
                @foreach (var ApplicantYear in ViewBag.Year)
                {
                    <option value="@ApplicantYear.Id">@ApplicantYear.Year</option>
                }
            </select>
        </div>
        <div class="col-md-2" style="margin-left:-20px;">
            <button onclick="applyFilter()" class="btn btn-primary">Filter</button>
        </div>
    </div>
  </div>

  <div class="col-sm-3">
        <div class="container row">
                <input class="col-sm-8" type="text" name="query" id="searchInput" placeholder="Enter Username" required>
                
                <button class="col-sm-3 search-icon" type="submit"  onclick="Search()">
                <i  class="bi bi-search"></i>
                </button>
        </div>
        <div id="UserNameEmpty" style="color:red;display:none;padding-left:60px">Enter UserName !</div>
  </div>
</div>


<br />
<div class="PartialViewResult">
<div class="container mt-4">

    @if (Model.Any())
    {
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Email</th>
                    <th>Application Detail</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var applicant in Model)
                {
                    <tr>
                        <td>@applicant.FirstName</td>
                        <td>@applicant.LastName</td>
                        <td>@applicant.ApplicationUser.Email</td>
                        <td>
                            <a href="javascript:void(0);" class="view-details-link" onclick="viewDetails(@applicant.Id)">View Details</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>Applicants is not Registered yet.</p>
    }  
</div>
</div>

<!-- Modal -->
<div class="modal fade" id="applicantDetailsModal" tabindex="-1" role="dialog"  aria-hidden="true">
    <div class="modal-dialog  modal-lg" role="document">
        <div class="modal-content">
            
            <div class="modal-body">
                <!-- Rendered applicant details will be displayed here -->
            </div>
            <div class="modal-footer">
                <button type="button" class=" btn-secondary" data-bs-dismiss="modal" aria-label="Close">Close</button>
                
            </div>
        </div>
    </div>
</div>

<script>
        function applyFilter() {
        var selectedYearId = document.getElementById('ApplicantFilter').value;


            $.ajax({
            url: '@Url.Action("Filter", "ApplicantStatus")',
                type: 'GET',
            data: { YearId: selectedYearId },
                success: function (result) {

                    $('.PartialViewResult').html(result);
                },
                error: function (error) {
                    console.error('Error:', error);
                }
            });
        }

    function Search() {
        var SearchedUsername = document.getElementById('searchInput').value.trim();

        if (SearchedUsername === '') {
            document.getElementById('UserNameEmpty').style.display = "block";
        }
        else {
            document.getElementById('UserNameEmpty').style.display = "none";
            $.ajax({
                url: '@Url.Action("Search", "ApplicantStatus")',
                type: 'GET',
                data: { SearchedUsername: SearchedUsername },
                success: function (result) {
                    $('.PartialViewResult').html(result);
                },
                error: function (error) {
                    console.error('Error:', error);
                }
            });
        }
    }



    function viewDetails(applicantId) {

        $.ajax({
            url: '@Url.Action("GetApplicantDetails", "ApplicantStatus")',
            type: 'GET',
            data: { applicantId: applicantId },
            success: function (result) {
                $('#applicantDetailsModal .modal-body').html(result);
                $('#applicantDetailsModal').modal('show');
            },
            error: function (error) {
                console.error('Error:', error);
            }
        });
    }
</script>

Views/ApplicantStatus/NotAssigned.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Access Denied</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f5f5f5;
            text-align: center;
            margin: 0;
            padding: 0;
        }

        .container {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
        }

        h1 {
            color: #ff6347;
            font-size: 36px;
            margin-bottom: 20px;
        }

        p {
            font-size: 18px;
            color: #333;
            margin-bottom: 20px;
        }

        a {
            text-decoration: none;
            color: #007bff;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Access Denied</h1>
        <p>Sorry, you don't have access to this page because you haven't been assigned to a department and university by the admin.</p>
        <p>Please contact the admin for assistance.</p>
        
    </div>
</body>
</html>

Views/ApplicantStatus/_ApplicantDetails.cshtml
@model InternshipDotCom.Models.ApplicantInternship

<div class="container">
    <h4>Applicant Details</h4>
    <hr />
    <div class="row">
        <div class="col-md-6">
            <dl class="row">
                <dt class="col-sm-6">First Name:</dt>
                <dd class="col-sm-6">@Model.FirstName</dd>

                <dt class="col-sm-6">Last Name:</dt>
                <dd class="col-sm-6">@Model.LastName</dd>

                <dt class="col-sm-6">Email:</dt>
                <dd class="col-sm-6">@Model.ApplicationUser.Email</dd>

                <dt class="col-sm-6">University:</dt>
                <dd class="col-sm-6">@Model.university.name</dd>

                <dt class="col-sm-6">Department:</dt>
                <dd class="col-sm-6">@Model.department.Name</dd>

                <dt class="col-sm-6">Year of Study:</dt>
                <dd class="col-sm-6">@Model.YearOfStudy.Year</dd>

                <dt class="col-sm-6">Interview Status:</dt>
                <dd class="col-sm-6">
                    @if (@Model.IsCalledForInterview)
                    {
                        if (@Model.IsInterviewAccepted)
                        {
                            @Html.Raw("Finished") 
                        }
                        else
                        {
                            @Html.Raw("Not Started") 
                        }
                    }
                    else
                    {
                        @Html.Raw("Not Started") 
                    }
                </dd>

                <dt class="col-sm-6">Internship Status:</dt>
                <dd class="col-sm-6">
                    @if (@Model.StartedInternship)
                    {
                        if (@Model.FinishedInternship)
                        {
                            @Html.Raw("Finished") 
                        }
                        else
                        {
                            @Html.Raw("On progress") 
                        }
                    }
                    else
                    {
                        @Html.Raw("Not started")
                    }
                </dd>
            </dl>
        </div>
    </div>
</div>

Views/ApplicantStatus/_ApplicantTable.cshtml
@model List<InternshipDotCom.Models.ApplicantInternship>

<div class="container mt-4">

    @if (Model.Any())
    {
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Email</th>
                    <th>Application Detail</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var applicant in Model)
                {
                    <tr>
                        <td>@applicant.FirstName</td>
                        <td>@applicant.LastName</td>
                        <td>@applicant.ApplicationUser.Email</td>
                        <td>
                            <a href="javascript:void(0);" class="view-details-link" onclick="viewDetails(@applicant.Id)">View Details</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No Registerd Applicant found that matches your request !!.</p>
    }
</div>