Models/Organization.cs
using Microsoft.AspNetCore.Identity;

namespace InternshipDotCom.Models
{
    public class Organization
    {
        public int Id { get; set; }

        public string OrganizationName { get; set; }

        public string Address { get; set; }

        public string Description { get; set; }

        // Foreign key to represent the ID of the user who created the organization
        public string ApplicationUserId { get; set; }

        // Navigation property to represent the user who created the organization
        public ApplicationUser ApplicationUser { get; set; }

        public ICollection<Internship> Internships { get; set; }
    }
}

Controllers/OrganizationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InternshipDotCom.Models;
using InternshipDotCom.Servieces;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;

namespace InternshipDotCom.Controllers
{
    [Authorize(Roles = "organization")]

    public class OrganizationsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OrganizationsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Organizations
        // GET: Organizations
        public async Task<IActionResult> Index()
        {
            // Get the current user's ID
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            // Retrieve organizations owned by the current user
            var organizations = await _context.Organization
                .Where(o => o.ApplicationUserId == userId)
                .ToListAsync();

            return View(organizations);
        }


        // GET: Organizations/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var organization = await _context.Organization
                .Include(o => o.ApplicationUser)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (organization == null)
            {
                return NotFound();
            }

            return View(organization);
        }

        // GET: Organizations/Create
        public IActionResult Create()
        {
           
            return View();
        }

        // POST: Organizations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,OrganizationName,Address,Description")] Organization organization)
        {
            
                // Set the ApplicationUserId property to the ID of the current user
                organization.ApplicationUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

                _context.Add(organization);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            
            
        }


        // GET: Organizations/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var organization = await _context.Organization.FindAsync(id);
            if (organization == null)
            {
                return NotFound();
            }
            ViewData["ApplicationUserId"] = new SelectList(_context.Users, "Id", "Id", organization.ApplicationUserId);
            return View(organization);
        }

        // POST: Organizations/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,OrganizationName,Address,Description")] Organization organization)
        {
            if (id != organization.Id)
            {
                return NotFound();
            }

            organization.ApplicationUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            try
                {
                    _context.Update(organization);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrganizationExists(organization.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
        }



        public async Task<IActionResult> ViewRegisteredStudents()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            // Retrieve organization IDs owned by the current user
            var userOrganizationIds = await _context.Organization
                .Where(o => o.ApplicationUserId == userId)
                .Select(o => o.Id)
                .ToListAsync();

            // Filter internships based on the organization IDs
            var internships = await _context.Internship
                .Include(i => i.Organization)
                .Where(i => userOrganizationIds.Contains(i.OrganizationId))
                .ToListAsync();

            // Retrieve the IDs of internships associated with the organizations
            var internshipIds = internships.Select(i => i.Id).ToList();

            // Retrieve registered students for these internships
            var registeredStudents = await _context.ApplicantInternship
                .Include(ai => ai.ApplicationUser)
                .Include(ai => ai.Internship)
                .Where(ai => internshipIds.Contains(ai.InternshipId) && ai.IsApplied)
                .ToListAsync();

            // Get unique organizations for which at least one student has applied
            var appliedOrganizationIds = registeredStudents.Select(rs => rs.Internship.OrganizationId).Distinct().ToList();

            // Retrieve organizations corresponding to these IDs
            var appliedOrganizations = await _context.Organization
                .Where(org => appliedOrganizationIds.Contains(org.Id))
                .ToListAsync();

            ViewBag.Organizations = appliedOrganizations;

            return View(registeredStudents);
        }


        public async Task<IActionResult> ViewApplicantDetails(string applicationUserId, int internshipId)
        {
            var applicant = await _context.ApplicantInternship
                .Include(ai => ai.ApplicationUser)
                .Include(ai => ai.Internship)
                .Include(i => i.department) 
                .Include(ai => ai.Internship)
                .Include(i => i.university)
                .Include(i => i.YearOfStudy)
                .FirstOrDefaultAsync(ai => ai.ApplicationUserId == applicationUserId && ai.InternshipId == internshipId);

            if (applicant == null)
            {
                return NotFound();
            }

            return PartialView("_ApplicantDetails", applicant);
        }





        public async Task<IActionResult> FilterApplicants(int? organizationId)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            // Retrieve organization IDs owned by the current user
            var userOrganizationIds = await _context.Organization
                .Where(o => o.ApplicationUserId == userId)
                .Select(o => o.Id)
                .ToListAsync();

            // Filter internships based on the organization IDs owned by the user
            IQueryable<Internship> internshipsQuery = _context.Internship
                .Include(i => i.Organization)
                .Where(i => userOrganizationIds.Contains(i.OrganizationId));

            // Filter internships based on the provided organization ID
            if (organizationId.HasValue)
            {
                internshipsQuery = internshipsQuery.Where(i => i.OrganizationId == organizationId);
            }

            // Retrieve the IDs of internships associated with the organizations
            var internshipIds = await internshipsQuery.Select(i => i.Id).ToListAsync();

            // Retrieve applicants who have applied for these internships
            var filteredApplicants = await _context.ApplicantInternship
                .Include(ai => ai.ApplicationUser)
                .Include(ai => ai.Internship) // Ensure Internship property is loaded
                .Where(ai => internshipIds.Contains(ai.InternshipId) && ai.IsApplied)
                .ToListAsync();

            // Get unique organizations for which at least one student has applied
            var appliedOrganizationIds = filteredApplicants.Select(ai => ai.Internship.OrganizationId).Distinct().ToList();

            // Retrieve organizations corresponding to these IDs
            var appliedOrganizations = await _context.Organization
                .Where(org => appliedOrganizationIds.Contains(org.Id))
                .ToListAsync();

            ViewBag.Organizations = appliedOrganizations;

            return PartialView("_FilteredApplicant", filteredApplicants);
        }


        public async Task<IActionResult> LoadApplicants(int page = 1)
        {
            var pageSize = 5;
            var skip = (page - 1) * pageSize;
            int totalItemCount = await _context.ApplicantInternship
                .Where(ai => ai.IsApplied)
                .CountAsync();
            ViewBag.TotalItemCount = totalItemCount;

            var applicants = await _context.ApplicantInternship
                .Include(ai => ai.ApplicationUser)
                .Include(ai => ai.Internship)
                .Where(ai => ai.IsApplied)
                .OrderBy(ai => ai.Id)
                .Skip(skip)
                .Take(pageSize)
                .ToListAsync();

            return PartialView("_FilteredApplicant", applicants);
        }


        [HttpPost]
        public async Task<IActionResult> CallForInterview(string applicationUserId, int internshipId, string interviewLink, DateOnly interviewDate, TimeSpan interviewTime)
        {

Views/Organizations/Create.cshtml
@model InternshipDotCom.Models.Organization

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml"; // Assuming you have a layout for consistent styling
}

<div class="container w-50">
    <div class="card">
        <div class="card-header">
            <h2 class="text-center">Add Companey</h2>
        </div>
        <div class="card-body">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="OrganizationName" class="control-label">Companey Name</label>
                    <input asp-for="OrganizationName" class="form-control" />
                    <span asp-validation-for="OrganizationName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Address" class="control-label">Address</label>
                    <input asp-for="Address" class="form-control" />
                    <span asp-validation-for="Address" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label">Description</label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block">Add</button>
                </div>
            </form>
        </div>
        <div class="card-footer">
            <a asp-action="Index" class="btn btn-secondary">Back </a>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Organizations/Delete.cshtml
@model InternshipDotCom.Models.Organization

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml"; // Assuming you have a layout for consistent styling
}

<div class="container" >
    <div class="card">
        <div class="card-header" style="background-color: orangered;">
            <h2 class="text-center">Delete Companey</h2>
        </div>
        <div class="card-body" style="background-color: #ffcccc;">
            <h3 class="text-center">Are you sure you want to delete this Companey?</h3>
            <dl class="row">
                <dt class="col-sm-3">Companey Name</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.OrganizationName)</dd>

                <dt class="col-sm-3">Address</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.Address)</dd>

                <dt class="col-sm-3">Description</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.Description)</dd>
            </dl>
        </div>
        <div class="card-footer" style="background-color: #ffcccc;">
            <form asp-action="Delete">
                <input type="hidden" asp-for="Id" />
                <button type="submit" class="btn btn-danger">Delete</button> 
                <a asp-action="Index" class="btn btn-secondary">Back</a>
            </form>
        </div>
    </div>
</div>

Views/Organizations/Details.cshtml
@model InternshipDotCom.Models.Organization

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml"; // Assuming you have a layout for consistent styling
}

<div class="container">
    <div class="card">
        <div class="card-header">
            <h2 class="text-center">Companey Details</h2>
        </div>
        <div class="card-body">
            
            <dl class="row">
                <dt class="col-sm-3">Companey Name</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.OrganizationName)</dd>

                <dt class="col-sm-3">Address</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.Address)</dd>

                <dt class="col-sm-3">Description</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.Description)</dd>
            </dl>
        </div>
        <div class="card-footer">
            <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-primary">Edit</a> 
            <a asp-action="Index" class="btn btn-secondary">Back</a>
        </div>
    </div>
</div>

Views/Organizations/Edit.cshtml
@model InternshipDotCom.Models.Organization

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml"; // Assuming you have a layout for consistent styling
}

<div class="container w-50">
    <div class="card">
        <div class="card-header">
            <h2 class="text-center">Edit Companey</h2>
        </div>
        <div class="card-body">
            
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <div class="form-group">
                    <label asp-for="OrganizationName" class="control-label">Companey Name</label>
                    <input asp-for="OrganizationName" class="form-control" />
                    <span asp-validation-for="OrganizationName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Address" class="control-label">Address</label>
                    <input asp-for="Address" class="form-control" />
                    <span asp-validation-for="Address" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label">Description</label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
        <div class="card-footer">
            <a asp-action="Index" class="btn btn-secondary">Back </a>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Organizations/ViewRegisteredStudents.cshtml
@model List<InternshipDotCom.Models.ApplicantInternship>

@{
    
    int pageSize = 5;
    int totalpageCount = Model.Count;
    int totalPages = (int)Math.Ceiling(Model.Count / (double)pageSize);
}

<style>
  
    .filter-container {
        margin-bottom: 20px;
    }

        .filter-container label {
            font-weight: bold;
        }

        .filter-container select {
            width: 100%;
            padding: 8px;
            border-radius: 5px;
            border: 1px solid #ccc;
        }

        .filter-container button {
            margin-top: 5px;
            padding: 8px 15px;
            border-radius: 5px;
            background-color: #007bff;
            color: #fff;
            border: none;
            cursor: pointer;
        }

    .applicant-table {
        width: 100%;
        border-collapse: collapse;
    }

        .applicant-table th,
        .applicant-table td {
            padding: 10px;
            border-bottom: 1px solid #ddd;
        }

        .applicant-table th {
            background-color: #f2f2f2;
            font-weight: bold;
            text-align: left;
        }

    .no-applicants {
        margin-top: 20px;
        font-style: italic;
        color: #777;
    }

    .pagination {
        margin-top: 20px;
        text-align: right; /* Align pagination to the right */
    }

        .pagination a {
            display: inline-block;
            padding: 5px 10px;
            margin-right: 5px;
            border: 1px solid #ccc;
            border-radius: 5px;
            color: #007bff;
            text-decoration: none;
        }

            .pagination a.active {
                background-color: #007bff;
                color: #fff;
            }

    .view-details-link {
        color: #007bff;
        text-decoration: none;
        border: 1px solid #007bff;
        padding: 5px 10px;
        border-radius: 5px;
        transition: background-color 0.3s ease;
        background-color: rgba(0, 123, 255, 0.1);
    }

        .view-details-link:hover {
            background-color: rgba(0, 123, 255, 0.2);
            color: #007bff;
        }



</style>


<div class="filter-container">
    <div class="row">
        <div class="col-md-2">
            <label for="organizationFilter">Filter by organization:</label>
        </div>
        <div class="col-md-3">
            <select id="organizationFilter">
                <option value="">All</option>
                @foreach (var organization in ViewBag.Organizations)
                {
                    <option value="@organization.Id">@organization.OrganizationName</option>
                }
            </select>
        </div>
        <div class="col-md-2">
            <button onclick="applyFilter()">Apply Filter</button>
        </div>
    </div>
</div>

<div class="applicant-list">
    @if (Model.Any())
    {
        <table class="applicant-table">
            <thead>
                <tr>
                    <th>Student Name</th>
                    <th>Email</th>
                    <th>Phone Number</th>
                    <th>Internship Name</th>
                    <th>Application Detail</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var registration in Model.Take(pageSize))
                {
                    <tr>
                        <td>@registration.ApplicationUser.FristName</td>
                        <td>@registration.ApplicationUser.Email</td>
                        <td>@registration.ApplicationUser.PhoneNumber</td>
                        <td>@(registration.Internship != null ? registration.Internship.InternshipName : "N/A")</td>
                        <td>
                            <a href="javascript:void(0);" onclick="viewApplicantDetails('@registration.ApplicationUserId', @registration.InternshipId)" class="view-details-link">View Details</a>
                        </td>


                    </tr>
                }
            </tbody>
        </table>

        @if (totalPages > 1 )
        {
            <div class="row">
                <div class="col-md-12">
                    <div class="pagination d-flex justify-content-end">
                        @for (int i = 1; i <= totalPages; i++)
                        {
                            <a class="@(i == 1 ? "active paginatedItem" : "paginatedItem")" onclick="changePage(@i)" style="cursor: pointer;">@i</a>
                        }
                    </div>
                </div>
            </div>
        }
       
    }
    else
    {
        <p class="no-applicants">No students registered for internships posted by this organization.</p>
    }
</div>
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Select Interview Date and Time</h4>
            </div>
            <div class="modal-body">
                <form id="interviewForm">
                    <div class="form-group">
                        <label for="interviewDate">Interview Date:</label>
                        <input type="date" class="form-control" id="interviewDate" required min="<%= DateTime.Now.ToString(" yyyy-MM-dd") %>" />
                    </div>
                    <div class="form-group">
                        <label for="interviewTime">Interview Time:</label>
                        <input type="time" class="form-control" id="interviewTime" required />
                    </div>
                    <br />
                    <button type="submit" class="btn btn-primary">Schedule Interview</button>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class=" btn-secondary" data-bs-dismiss="modal" aria-label="Close">Close</button>
            </div>
        </div>
    </div>
</div>


<div id="applicant-details-container"></div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>

        var nowTime = new Date();
        var currentDate = nowTime.toISOString().split('T')[0];
        document.getElementById('interviewDate').setAttribute('min', currentDate);


        function applyFilter() {
            var selectedOrganizationId = $('#organizationFilter').val();

            $.ajax({
                url: '@Url.Action("FilterApplicants", "Organizations")',
                type: 'GET',
                data: { organizationId: selectedOrganizationId },
                success: function (result) {
                    $('.applicant-list').html(result);
                },
                error: function (error) {
                    console.error('Error:', error);
                }
            });
        }
        function viewApplicantDetails(applicationUserId, internshipId) {
            
            $.ajax({
                url: '@Url.Action("ViewApplicantDetails", "Organizations")',
                type: 'GET',
                data: { applicationUserId: applicationUserId, internshipId: internshipId },
                success: function (result) {
                    $('#applicant-details-container').html(result);
                    displayApplicantDetails();
                },
                error: function (error) {
                    console.error('Error:', error);
                }
            });
        }


        function callForInterview(applicationUserId, internshipId, interviewDate, interviewTime) {
            var now = new Date();
            var currentDate = new Date(now.getFullYear(), now.getMonth(), now.getDate());
            var currentTime = now.getHours() * 60 + now.getMinutes(); // Convert current time to minutes

            // Parse the interview date and time
            var interviewDateStr = interviewDate;
            var interviewDateComponents = interviewDateStr.split('/');
            var parsedInterviewDate = new Date(
                parseInt(interviewDateComponents[2]),  // Year
                parseInt(interviewDateComponents[1]) - 1,  // Month (zero-based index)
                parseInt(interviewDateComponents[0])   // Day
            );

            var parsedInterviewTime = interviewTime.split(':').map(Number);
            var interviewDateTime = new Date(parsedInterviewDate.getFullYear(), parsedInterviewDate.getMonth(), parsedInterviewDate.getDate(), parsedInterviewTime[0], parsedInterviewTime[1]);

            // Calculate the time difference in minutes between now and the interview date and time
            var timeDifference = (interviewDateTime - now) / (1000 * 60);

            // Select the button element
            var buttonElement = $('#call-interview-button');

          
            var googleMeetLink = "https://meet.google.com/gti-xdcd-qyp";
            $.ajax({
                url: '@Url.Action("CallForInterview", "Organizations")',
                type: 'POST',
                data: { applicationUserId: applicationUserId, internshipId: internshipId, interviewLink: googleMeetLink, interviewDate: interviewDate, interviewTime: interviewTime },
                success: function (response) {
                    if (response.success) {
                        // Update the button text based on the interview date and time
                        if (timeDifference < -2) {
                            
                            buttonElement.replaceWith('<p style="font-weight: bold; color: red;">Interview Passed</p>');

                        }
                        else if (timeDifference >= -2 && timeDifference <= 0) {

                            buttonElement.replaceWith(' <button class="btn btn-sm btn-outline-primary " onclick="window.location.href = interviewLink">Start Interview</button>');

                        } else {
                          
                            buttonElement.replaceWith('<p style="font-weight: bold; color: green;">Interview Coming Soon</p>');
                        }
                    } else {
                        console.error('Failed to call applicant for interview.');
                    }
                },
                error: function (error) {
                    console.error('Error:', error);
                }
            });
        }


        function startInternship(applicationUserId, internshipId) {
            var buttonElement = $('#hire-intern-button');
            $.ajax({
                url: '@Url.Action("startInternship", "Organizations")',
                type: 'POST',
                data: { applicationUserId: applicationUserId, internshipId: internshipId },
                success: function (result) {
                    buttonElement.replaceWith('<p style="font-weight: bold; color: green;">Hired</p>');
                },
                error: function (error) {
                    console.error('Error:', error);
                }
            });
        }


        function finishInternship(applicationUserId, internshipId) {

            var buttonElement = $('#finish-internship-button');

            $.ajax({
                url: '@Url.Action("finishInternship", "Organizations")',
                type: 'POST',
                data: { applicationUserId: applicationUserId, internshipId: internshipId },
                success: function (result) {

                    buttonElement.replaceWith('<p style="font-weight: bold; color: green;">Finished Internship</p>');

                },
                error: function (error) {
                    console.error('Error:', error);
                }
            });
        }

        function displayApplicantDetails() {
            
            $('#applicant-details-container').show();
        }

        function closeDetails() {
        
            $('#applicant-details-container').hide();
        }



        function changePage(pageNumber) {

           
            $.ajax({
                url: '@Url.Action("LoadApplicants", "Organizations")',
                type: 'GET',
                data: { page: pageNumber },
                success: function (result) {
                    $('.applicant-list').html(result);

                    let active = document.getElementsByClassName('paginatedItem');
                    let i;
                    for (i = 0; i < active.length; i++) {
                        active[i].className = active[i].className.replace(' active', '');
                    }
                    active[i].className += " active";
                   
                },
                error: function (error) {
                    console.error('Error:', error);
                }
            });
        }

        var ApplicationUserId;
        var InternshipId;


        function openModal(applicationUserId,internshipId) {
            ApplicationUserId = applicationUserId;
            InternshipId = internshipId;
            $('#myModal').modal('show');
        }

        $('#interviewForm').submit(function (event) {
            event.preventDefault();
            var interviewDate = $('#interviewDate').val();
            var interviewTime = $('#interviewTime').val();

            // Pass the interview date and time to the callForInterview function
            callForInterview(ApplicationUserId, InternshipId, interviewDate, interviewTime);

            // Close the modal
            $('#myModal').modal('hide');
        });

    </script>
}